FROM baseos
MAINTAINER tramy tramy1234@163.com
RUN apk add python
RUN apk add py2-pip
RUN pip install flask
RUN pip install redis
RUN pip install flask-bootstrap
RUN mkdir -p /app
# this cmd will run on start
# CMD ["echo","flask already install"]
#CMD /bin/sh
 

